run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - revive
    - unused
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - gosimple
    - depguard
    - gocyclo
    - dupl
    - nakedret
    - unconvert
    - unparam
    - exportloopref
    - prealloc
    - interfacer
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - godot
    - godox
    - nolintlint
    - forbidigo
    - lll
    - whitespace
    - stylecheck
    - scopelint
    - gosec
    - dogsled
    - errorlint
    - exhaustivestructs
    - exhaustive
    - forbidigo
    - gci
    - goheader
    - gomnd
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - wastedassign
    - wrapcheck
    - zerolog
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - golint
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - wrapcheck
    - zerolog
    - dogsled
    - bidichk
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - decorder
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - golint
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - wrapcheck
    - zerolog
